defaults: &defaults
  working_directory: ~/grafana-sensu-app
  docker:
    - image: circleci/node:10.14.2-stretch

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn
      - run: node -p "require('node-sass').info"
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: build
          command: yarn build
  test:
    <<: *defaults
    steps:
      - checkout
      - run: yarn test

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
