defaults: &defaults
  working_directory: ~/grafana-sensu-app
  docker:
    - image: circleci/node:10.9.0-jessie

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run: yarn
      - run: node -p "require('node-sass').info"
      - save_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: build
          command: yarn build
  test:
    <<: *defaults
    steps:
      - checkout
      - run: yarn test

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
