defaults: &defaults
  working_directory: ~/grafana-sensu-app
  docker:
    - image: circleci/node:7.10

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@6.4.0'
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - run: npm cache clean && npm install
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run grunt
          command: |
            grunt
  grunttest:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Test
          command: grunt test

workflows:
  version: 2

  build-test:
    jobs:
      - build
      - grunttest:
          requires:
            - build
