defaults: &defaults
  working_directory: ~/grafana-sensu-app
  docker:
    - image: circleci/node:7.10

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-{{ checksum "bower.json" }}
      - run: bower install
      - run: npm install
      - save_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-{{ checksum "bower.json" }}
      - run:
          name: Run grunt
          command: |
            grunt
  grunttest:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Test
          command: grunt test

workflows:
  version: 2

  build-test:
    jobs:
      - build
      - grunttest:
          requires:
            - build
